spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barberapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # or none; Flyway manages schema
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true  # Only needed if schema already exists

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_FROM_NUMBER}
  appointment-reminder:
    enabled: true
    reminder-time: 30 # in minutes
    message: "⏰ Reminder: Your appointment at {formattedTime} (in {time} minutes)"
    time-zone: "Europe/Amsterdam"
  sms-notification:
    enabled: true
    message: "✅ Appointment confirmed! We'll send a reminder 30 minutes before."
    time-zone: "Europe/Amsterdam"
