spring:
  datasource:
    url: jdbc:h2:mem:barberdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update  # Use 'create' for dev-only or 'validate' for prod
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_FROM_NUMBER}
  appointment-reminder:
    enabled: true
    reminder-time: 30 # in minutes
    message: "⏰ Reminder: Your appointment at {formattedTime} (in {time} minutes)"
    time-zone: "Europe/Amsterdam"
  sms-notification:
    enabled: true
    message: "✅ Appointment confirmed! We'll send a reminder 30 minutes before."
    time-zone: "Europe/Amsterdam"
