name: Run Java Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test
        run: mvn clean test

      - name: Upload test reports
        uses: actions/upload-artifact@v4.6.2
        with:
          name: junit-results
          path: target/surefire-reports/
